### ISSUE TITLE
Get OS version, dist, node-version, package.json deps versions information

### ISSUE THREAD

**Issue by dantehemerson** [dantehemerson/fons#8]
In order to make easy get os info.

**Reasons**
Some issues templates in Github required information to report that issues. 
e.g.
![image](https://user-images.githubusercontent.com/18385321/95004287-e5a24f00-05ae-11eb-94f2-bef41a4cb512.png)

So I need an easy way to get that info via CLI.

You can use the [`os`](https://nodejs.org/api/os.html) module from nodejs

**Comment by scampiuk** [comment]
Many appologies, I named the branch wrong, but open PR in https://github.com/dantehemerson/fons/pull/9

**Comment by dantehemerson** [comment]
Closed via #9

**Comment by scampiuk** [comment]
:bow:
